# This is a basic workflow to help you get started with Actions

name: UI Tests - Chrome

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ui-tests-chrome:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Ping API (Heroku)
        uses: Leocardoso94/is-my-site-up@v1.2
        with:
          site: https://samuraibarbershop-api-cassio.herokuapp.com

      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v4
        with:
          # we have already installed all dependencies above
          install-command: yarn install
          wait-on: 'https://samuraibarbershop-web-cassio.herokuapp.com'
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
          spec: cypress/integration/*
        env:
          TZ: America/Sao_Paulo
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
